create extension if not exists pgcrypto with schema extensions;

create table if not exists public.account_recovery_methods (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  question text not null check (char_length(question) between 2 and 100),
  answer_hash text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.account_recovery_attempts (
  id bigint generated by default as identity primary key,
  username text not null,
  succeeded boolean not null default false,
  attempted_at timestamptz not null default now()
);
create index if not exists account_recovery_attempts_lookup_idx on public.account_recovery_attempts(username, attempted_at desc);

alter table public.account_recovery_methods enable row level security;
alter table public.account_recovery_attempts enable row level security;
revoke all on public.account_recovery_methods, public.account_recovery_attempts from anon, authenticated;

create or replace function public.set_my_recovery_method(target_question text, target_answer text)
returns void language plpgsql security definer set search_path = public, extensions as $$
declare actor_profile_id uuid;
begin
  select id into actor_profile_id from public.profiles where auth_user_id = auth.uid();
  if actor_profile_id is null then raise exception 'profile_not_found'; end if;
  if char_length(trim(target_question)) < 2 or char_length(trim(target_answer)) < 2 then raise exception 'invalid_recovery_method'; end if;
  insert into public.account_recovery_methods(profile_id, question, answer_hash, updated_at)
  values (actor_profile_id, trim(target_question), crypt(lower(trim(target_answer)), gen_salt('bf')), now())
  on conflict (profile_id) do update set question = excluded.question, answer_hash = excluded.answer_hash, updated_at = now();
end; $$;
revoke all on function public.set_my_recovery_method(text,text) from public;
grant execute on function public.set_my_recovery_method(text,text) to authenticated;

create or replace function public.get_recovery_question(target_username text, target_nickname text)
returns text language sql stable security definer set search_path = public as $$
  select r.question from public.account_recovery_methods r join public.profiles p on p.id = r.profile_id
  where lower(p.username) = lower(trim(target_username)) and lower(trim(p.nickname)) = lower(trim(target_nickname));
$$;
revoke all on function public.get_recovery_question(text,text) from public;
grant execute on function public.get_recovery_question(text,text) to anon, authenticated;

create or replace function public.verify_recovery_answer(target_username text, target_nickname text, target_answer text)
returns uuid language plpgsql security definer set search_path = public, extensions as $$
declare normalized_username text := lower(trim(target_username)); target_auth_user_id uuid; stored_hash text; recent_failures int;
begin
  select count(*) into recent_failures from public.account_recovery_attempts
  where username = normalized_username and succeeded = false and attempted_at >= now() - interval '30 minutes';
  if recent_failures >= 5 then raise exception 'recovery_temporarily_locked'; end if;
  select p.auth_user_id, r.answer_hash into target_auth_user_id, stored_hash
  from public.profiles p join public.account_recovery_methods r on r.profile_id = p.id
  where lower(p.username) = normalized_username and lower(trim(p.nickname)) = lower(trim(target_nickname));
  if target_auth_user_id is null or stored_hash <> crypt(lower(trim(target_answer)), stored_hash) then
    insert into public.account_recovery_attempts(username, succeeded) values(normalized_username, false);
    return null;
  end if;
  insert into public.account_recovery_attempts(username, succeeded) values(normalized_username, true);
  return target_auth_user_id;
end; $$;
revoke all on function public.verify_recovery_answer(text,text,text) from public, anon, authenticated;
grant execute on function public.verify_recovery_answer(text,text,text) to service_role;
