-- 관리자 전용 가입/접속 통계. 개인 주방 데이터는 수집하지 않습니다.

create table if not exists public.app_usage_events (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null default 'app_open' check (event_type in ('app_open')),
  occurred_at timestamptz not null default now()
);

create index if not exists app_usage_events_profile_time_idx
  on public.app_usage_events(profile_id, occurred_at desc);
create index if not exists app_usage_events_time_idx
  on public.app_usage_events(occurred_at desc);

alter table public.app_usage_events enable row level security;

-- 클라이언트 직접 조회/수정은 허용하지 않고 보안 함수로만 기록·집계합니다.
revoke all on public.app_usage_events from anon, authenticated;
revoke all on sequence public.app_usage_events_id_seq from anon, authenticated;

create or replace function public.record_app_visit()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_profile_id uuid;
begin
  select id into actor_profile_id
  from public.profiles
  where auth_user_id = auth.uid();

  if actor_profile_id is null then return; end if;

  -- 새로고침마다 중복되지 않도록 사용자별 30분에 한 번만 방문으로 기록합니다.
  if not exists (
    select 1 from public.app_usage_events
    where profile_id = actor_profile_id
      and occurred_at >= now() - interval '30 minutes'
  ) then
    insert into public.app_usage_events(profile_id) values (actor_profile_id);
  end if;
end;
$$;

revoke all on function public.record_app_visit() from public;
grant execute on function public.record_app_visit() to authenticated;

create or replace function public.get_admin_usage_analytics()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with profile_stats as (
    select
      count(*)::int as total_users,
      count(*) filter (where created_at >= now() - interval '7 days')::int as new_users_7d,
      count(*) filter (where created_at >= date_trunc('day', now() at time zone 'Asia/Seoul') at time zone 'Asia/Seoul')::int as new_users_today
    from public.profiles
  ), event_stats as (
    select
      count(distinct profile_id) filter (where occurred_at >= date_trunc('day', now() at time zone 'Asia/Seoul') at time zone 'Asia/Seoul')::int as active_today,
      count(distinct profile_id) filter (where occurred_at >= now() - interval '7 days')::int as active_7d,
      count(*) filter (where occurred_at >= date_trunc('day', now() at time zone 'Asia/Seoul') at time zone 'Asia/Seoul')::int as visits_today
    from public.app_usage_events
  ), daily as (
    select jsonb_agg(jsonb_build_object(
      'date', days.day::date,
      'signups', (select count(*) from public.profiles p where (p.created_at at time zone 'Asia/Seoul')::date = days.day::date),
      'activeUsers', (select count(distinct e.profile_id) from public.app_usage_events e where (e.occurred_at at time zone 'Asia/Seoul')::date = days.day::date),
      'visits', (select count(*) from public.app_usage_events e where (e.occurred_at at time zone 'Asia/Seoul')::date = days.day::date)
    ) order by days.day) as value
    from generate_series((current_date - 13)::timestamp, current_date::timestamp, interval '1 day') days(day)
  ), hourly as (
    select jsonb_agg(jsonb_build_object(
      'hour', hours.hour,
      'visits', (select count(*) from public.app_usage_events e where e.occurred_at >= now() - interval '30 days' and extract(hour from e.occurred_at at time zone 'Asia/Seoul') = hours.hour)
    ) order by hours.hour) as value
    from generate_series(0, 23) hours(hour)
  ), recent_users as (
    select jsonb_agg(to_jsonb(row_data) order by row_data.created_at desc) as value
    from (
      select p.id, p.username, p.nickname, p.created_at,
        (select max(e.occurred_at) from public.app_usage_events e where e.profile_id = p.id) as last_seen_at
      from public.profiles p
      order by p.created_at desc
      limit 30
    ) row_data
  )
  select case when public.is_app_admin() then jsonb_build_object(
    'totalUsers', profile_stats.total_users,
    'newUsers7d', profile_stats.new_users_7d,
    'newUsersToday', profile_stats.new_users_today,
    'activeToday', event_stats.active_today,
    'active7d', event_stats.active_7d,
    'visitsToday', event_stats.visits_today,
    'daily', coalesce(daily.value, '[]'::jsonb),
    'hourly', coalesce(hourly.value, '[]'::jsonb),
    'recentUsers', coalesce(recent_users.value, '[]'::jsonb)
  ) else null end
  from profile_stats, event_stats, daily, hourly, recent_users;
$$;

revoke all on function public.get_admin_usage_analytics() from public;
grant execute on function public.get_admin_usage_analytics() to authenticated;
